package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Auditorium;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface AuditoriumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.auditorium
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    int deleteByPrimaryKey(@Param("theatreId") String theatreId, @Param("nr") Integer nr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.auditorium
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    int insert(Auditorium record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.auditorium
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    Auditorium selectByPrimaryKey(@Param("theatreId") String theatreId, @Param("nr") Integer nr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.auditorium
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    List<Auditorium> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.auditorium
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    int updateByPrimaryKey(Auditorium record);
}