package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Movie;
import org.mybatis.cdi.Mapper;

@Mapper
public interface MovieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movie
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    int deleteByPrimaryKey(String eidr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movie
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    int insert(Movie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movie
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    Movie selectByPrimaryKey(String eidr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movie
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    List<Movie> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movie
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    int updateByPrimaryKey(Movie record);
}