package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.MovieTheatre;
import org.mybatis.cdi.Mapper;

@Mapper
public interface MovieTheatreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movie_theatre
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movie_theatre
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    int insert(MovieTheatre record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movie_theatre
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    MovieTheatre selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movie_theatre
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    List<MovieTheatre> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.movie_theatre
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    int updateByPrimaryKey(MovieTheatre record);
}