package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.TheatreMovies;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface TheatreMoviesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.theatre_movies
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    int deleteByPrimaryKey(@Param("theatreId") String theatreId, @Param("movieEidr") String movieEidr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.theatre_movies
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    int insert(TheatreMovies record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.theatre_movies
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    List<TheatreMovies> selectAll();
}