package lt.vu.mybatis.model;

public class Auditorium {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.auditorium.theatre_id
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    private String theatreId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.auditorium.nr
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    private Integer nr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.auditorium.seats
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    private Integer seats;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.auditorium.theatre_id
     *
     * @return the value of public.auditorium.theatre_id
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public String getTheatreId() {
        return theatreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.auditorium.theatre_id
     *
     * @param theatreId the value for public.auditorium.theatre_id
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public void setTheatreId(String theatreId) {
        this.theatreId = theatreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.auditorium.nr
     *
     * @return the value of public.auditorium.nr
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public Integer getNr() {
        return nr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.auditorium.nr
     *
     * @param nr the value for public.auditorium.nr
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public void setNr(Integer nr) {
        this.nr = nr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.auditorium.seats
     *
     * @return the value of public.auditorium.seats
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public Integer getSeats() {
        return seats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.auditorium.seats
     *
     * @param seats the value for public.auditorium.seats
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public void setSeats(Integer seats) {
        this.seats = seats;
    }
}