package lt.vu.mybatis.model;

import lombok.Getter;

import java.util.List;

public class MovieTheatre {
    private List<Movie> movies;
    private List<Auditorium> auditoriums;

    public List<Movie> getMovies() {
        return this.movies;
    }
    public List<Auditorium> getAuditoriums() {
        return this.auditoriums;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.movie_theatre.id
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.movie_theatre.address
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.movie_theatre.name
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.movie_theatre.id
     *
     * @return the value of public.movie_theatre.id
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.movie_theatre.id
     *
     * @param id the value for public.movie_theatre.id
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.movie_theatre.address
     *
     * @return the value of public.movie_theatre.address
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.movie_theatre.address
     *
     * @param address the value for public.movie_theatre.address
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.movie_theatre.name
     *
     * @return the value of public.movie_theatre.name
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.movie_theatre.name
     *
     * @param name the value for public.movie_theatre.name
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public void setName(String name) {
        this.name = name;
    }
}