package lt.vu.mybatis.model;

public class Movie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.movie.eidr
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    private String eidr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.movie.director
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    private String director;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.movie.name
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.movie.year
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    private Integer year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.movie.genres
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    private String genres;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.movie.duration
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    private Integer duration;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.movie.eidr
     *
     * @return the value of public.movie.eidr
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public String getEidr() {
        return eidr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.movie.eidr
     *
     * @param eidr the value for public.movie.eidr
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public void setEidr(String eidr) {
        this.eidr = eidr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.movie.director
     *
     * @return the value of public.movie.director
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.movie.director
     *
     * @param director the value for public.movie.director
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public void setDirector(String director) {
        this.director = director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.movie.name
     *
     * @return the value of public.movie.name
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.movie.name
     *
     * @param name the value for public.movie.name
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.movie.year
     *
     * @return the value of public.movie.year
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.movie.year
     *
     * @param year the value for public.movie.year
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.movie.genres
     *
     * @return the value of public.movie.genres
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public String getGenres() {
        return genres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.movie.genres
     *
     * @param genres the value for public.movie.genres
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public void setGenres(String genres) {
        this.genres = genres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.movie.duration
     *
     * @return the value of public.movie.duration
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.movie.duration
     *
     * @param duration the value for public.movie.duration
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }
}