package lt.vu.mybatis.model;

public class TheatreMovies {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.theatre_movies.theatre_id
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    private String theatreId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.theatre_movies.movie_eidr
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    private String movieEidr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.theatre_movies.theatre_id
     *
     * @return the value of public.theatre_movies.theatre_id
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public String getTheatreId() {
        return theatreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.theatre_movies.theatre_id
     *
     * @param theatreId the value for public.theatre_movies.theatre_id
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public void setTheatreId(String theatreId) {
        this.theatreId = theatreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.theatre_movies.movie_eidr
     *
     * @return the value of public.theatre_movies.movie_eidr
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public String getMovieEidr() {
        return movieEidr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.theatre_movies.movie_eidr
     *
     * @param movieEidr the value for public.theatre_movies.movie_eidr
     *
     * @mbg.generated Mon Mar 01 21:24:53 EET 2021
     */
    public void setMovieEidr(String movieEidr) {
        this.movieEidr = movieEidr;
    }
}